### ISSUE TITLE
SingleFile archive and/or arbitrary files linked to an entry

### ISSUE THREAD

**Issue by lyonzy** [linkwarden/linkwarden#192]
**Is your feature request related to a problem? Please describe.**
My problem is twofold (might be overloading this issue but didn't want to spam). Firstly the PDF extractor isn't perfect (although it's pretty good) - some deferred images in pages didn't get picked up. Also sometimes I want to save an interactive page (although not sure any tool will do that super reliably). Secondly, some pages I want to keep are originally not HTML (e.g. PDF, or video), and it doesn't look like the conversion process works for at least PDFs (understandable that the PDF converter would find PDF->PDF a confusing request).

**Describe the solution you'd like**
Pages to be processed with SingleFile or similar and that to be added to an entry - and/or - the ability to upload arbitrary files (consider Calibre-Web's functionality to upload various formats of a book).

**Comment by daniel31x13** [comment]
We just added a new archivable format in [v1.2.0](https://github.com/linkwarden/linkwarden/releases/tag/v1.2.0): Wayback Machine

**Comment by daniel31x13** [comment]
Adding this as a todo.

**Comment by brandonkal** [comment]
What would really be useful is to use a separate microservice dedicated to creating archives. This improves the flexibility of Linkwarden:
When Linkwarden receives a request for a URL, it sends a request to the archiving microservice container. The archiver service then drives Puppeteer, uses extensions such as SingleFile etc, or even uses a scraping API or proxy and then returns the results.

This gives the users of Linkwarden the ability to customize the archival process e.g. using an ad blocker, transforming and cleaning HTML, using a different IP, skipping the overhead of puppeteer when it is not necessary, failing back to a paid scraping API on errors, etc.

The microservice could return a well-formed REST response so that users can append links to the archived formats (ePub, hosted video archives, etc)

**Comment by daniel31x13** [comment]
Added in [v2.6.0](https://github.com/linkwarden/linkwarden/releases/tag/v2.6.0).

**Comment by huyz** [comment]
Out of curiosity, why was Monolith chosen over SingleFile (which supports JS)? Simpler and more lightweight?

**Comment by daniel31x13** [comment]
> Simpler and more lightweight?

This, and also Monolith *[does](https://github.com/Y2Z/monolith?tab=readme-ov-file#dynamic-content)* support javascript, I just needed to use playwright as the pre-processor.
