### ISSUE TITLE
When registration is disable the link to sign up is still on the login page. confusing.

### ISSUE THREAD

**Issue by PatCas71** [linkwarden/linkwarden#259]
All in the title.

**Comment by daniel31x13** [comment]
Hello @PatCas71,
The registration is disabled from the server side, meaning that there is _no_ way anyone could register after you set `NEXT_PUBLIC_DISABLE_REGISTRATION` to `true`.

The client side is not affected by the environment variable because [we can't change the client side environment variables in NextJS after the build](https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables#bundling-environment-variables-for-the-browser), and since the docker image was built without defining the `NEXT_PUBLIC_DISABLE_REGISTRATION`, the changes will only be affected on the server side.

(Worth noting that if you build the docker image _locally_, you'll see that the "Sign Up" link is gone.)
