### ISSUE TITLE
Importer hangs when importing (relatively) large .html files

### ISSUE THREAD

**Issue by linuxd3v** [linkwarden/linkwarden#260]
**Describe the bug**  
Unable to import bookmarks using .html file export if have a lot of bookmars (> 1Mb file).      My bookmarks .html file was only 1.5Mb.  
  
**To Reproduce**
1. Export bookmarks from  firefox
2. Click on Setting -> import from
3. Pick the .html bookmars export file
4. The import spinner keeps spinning forever, and Im seeing this error in the console:  

> Failed to load resource: the server responded with a status of 413 (Body exceeded 1mb limit)
account:1  Uncaught (in promise) SyntaxError: Unexpected token 'B', "Body excee"... is not valid JSON

**Expected behavior**
Bookmarks should have been imported   
  
**Screenshots**
![image](https://github.com/linkwarden/linkwarden/assets/3410509/3786a8aa-7d12-4763-8535-1f6ab5c351e6)

**Desktop (please complete the following information):**
 - OS: fedora 38
 - Browser: edge
 - Version Version 118.0.2088.61 (Official build) (64-bit)   

**Additional context**
My bookmarks .html file was only 1.5Mb.  

the solution is likely simply upping the body size limit: https://nextjs.org/docs/app/api-reference/functions/server-actions#size-limitation or making it configurable in docker-compose.yml

**Comment by daniel31x13** [comment]
Hello @linuxd3v, 
Thanks for pointing this out, just fixed it and the issue will we resolved in the next release.

**Comment by RogueGhost93** [comment]
any chance you can tell us exactly in which file is that option located so i can change it? Im eager to use the app but cant import at the moment and im too impatient to wait for next release :) Thanks!

**Comment by daniel31x13** [comment]
Sorry, there's been A LOT going on over here. So many code refactoring and stuff like that.
The next release (v2.0.0) will be ready before Friday. (It'll probably be much earlier...)
Also I wouldn't touch the underlying code if I were you. :)

**Comment by daniel31x13** [comment]
Fixed in [v2.0.0](https://github.com/linkwarden/linkwarden/releases/tag/v2.0.0).

**Comment by RogueGhost93** [comment]
So, i just tested the latest version.
For some reason i cant import my bookmarks. 

1 thing worked but i dont know why. Here is what i did.
1. Export bookmarks from linkding to Netscape html  (size 270KB) with tags and then import to Linkwarden --> this doesnt work, it just says bookmarks are imported but none are
2. That same file when imported to my CLEAN installation firefox and then exported out to html file (size ~270KB) and then imported to linkwarden also does the same thing, previously i thought this option was a workaround as it worked the first time i did it which brings me to 3. thing i did
3. I deleted all bookmarks and folders from my firefox but left the tags untouched, imported the html from linkwarden, exported it out and somehow that file is around 9MB now, i dont know why. That file somehow magically gets imported to linkwarden without issues, however it reports completely wrong things, it shows that i have 4k links, 170 collection and 260 tags which is not true for sure as i only have 1097 links  that were previously exported from linkding. I attached screenshot to show you, i will also attach log file from portainer which to me shows absolutely nothing. I dont know what could be the problem.
![Screenshot_20231108_1358
[_linkwarden_logs-3.txt](https://github.com/linkwarden/linkwarden/files/13296938/_linkwarden_logs-3.txt)
22](https://github.com/linkwarden/linkwarden/assets/127423999/8b5d1f37-d36e-491c-9e08-4c5f9512c17f)

im running 3 instances of linkwarden. 1 behind traefik and 2 regular ones. Same issue on all 3. I really love the app and design of it and im really eager to use it and im getting desparate here so i really hope you manage to resolve this or figure out what could be the problem. Maybe you can tell me how to increase logging so i can provide you with more verbose. I also have discord if you find chat to be easier for this kind of stuff, maybe i can help. I would give you my html file to test it but it does have some sensitive bookmarks so that option is a no go :/

**Comment by daniel31x13** [comment]
Replied in #271, marking this issue as complete...
