### ISSUE TITLE
Save WeChat article without pictures

### ISSUE THREAD

**Issue by klsdfjo** [linkwarden/linkwarden#340]
When I try to save a WeChat article, I only see text and no pictures. What's wrong?
![CleanShot 2023-12-13 at 19 08 56](https://github.com/linkwarden/linkwarden/assets/53525622/b15b2776-2247-4bd4-931f-20f1c206f45d)

wechat link:https://mp.weixin.qq.com/s/xI1fAX2ilJyE8NthrShU7g

My system is: debian11

**Comment by daniel31x13** [comment]
Hello @klsdfjo, the archive functionality may perform differently on every webpage.
This most likely related to how the webpage is performing.
This is the reason Linkwarden has multiple preserved formats for each webpage, so that if one format might have errors, another can step in to fill those gaps.

**Comment by klsdfjo** [comment]
Thanks Bro~
