### ISSUE TITLE
Archiver doesn't work in 2.4.1 when using a custom storage path and running as non-root

### ISSUE THREAD

**Issue by samip5** [linkwarden/linkwarden#369]
**Describe the bug**
Adding an URL to a collection results in an playwright error due to not finding an executeable as it's trying to find it at /.cache/*.

**To Reproduce**
1. Run Linkwarden without root privileges aka non-privileged
2. Add link to an collection
3. See the error in processing that said link

**Expected behavior**
I would have expected it to find the chrome executable.

**Screenshots**
![Screenshot of log](https://z.skylab.fi/i/2023-12-28_14-30-21.png)

**Comment by daniel31x13** [comment]
> 1. Run Linkwarden without root privileges aka non-privileged

Well does it work in root privileges? I remember in another issue a user pointing this out as well and the problem was for not running as root.

**Comment by samip5** [comment]
> the problem was for not running as root.

Sorry, but that's not the fix and I'm not conformable running it as root. The issue is that node should be instructed to use the storage path which appears to be using it's default which will not work even if running as root if rootFilesystem is read-only.

**Comment by daniel31x13** [comment]
This is what exactly happens when the app creates a file, feel free to check it out:
https://github.com/linkwarden/linkwarden/blob/main/lib/api/storage/createFile.ts

**Comment by samip5** [comment]
> This is what exactly happens when the app creates a file, feel free to check it out: https://github.com/linkwarden/linkwarden/blob/main/lib/api/storage/createFile.ts

I'm in the Discord. https://discord.com/channels/1117993124669702164/1123628004145369149/1189905698025373716

**Comment by samip5** [comment]
After setting `HOME` env variable to my storage path, and running `npx playwright install` it was able to install them and then it started to work even without root. This sounds like the container building might need some additional things..

**Comment by daniel31x13** [comment]
Ok sounds good.
Gonna change it later... Thanks for pointing it out.

**Comment by discotimetraveler** [comment]
I am having this same issue on my NAS. I did not install using the standard process and am running as non-root. But in my attempts to resolve this I'm a bit confused. Since this is on my NAS I'm not sure where/how I would run `npx playwright install` (not looking to install dev tools on my NAS, and this should  already be in the container?). This is the error I get...

Executable doesn't exist at /.cache/ms-playwright/chromium-1067/chrome-linux/chrome

When I log into the container and poke around for chrome I find...

./data/node_modules/playwright-core/lib/server/chromium

Which is not even close to the path in the error.  

I attempted to set HOME env variable to ideally change the behavior but no luck. 

Any suggestions?  Thanks

**Comment by samip5** [comment]
> I am having this same issue on my NAS. I did not install using the standard process and am running as non-root. But in my attempts to resolve this I'm a bit confused. Since this is on my NAS I'm not sure where/how I would run `npx playwright install` (not looking to install dev tools on my NAS, and this should already be in the container?). This is the error I get...
> 
> Executable doesn't exist at /.cache/ms-playwright/chromium-1067/chrome-linux/chrome
> 
> When I log into the container and poke around for chrome I find...
> 
> ./data/node_modules/playwright-core/lib/server/chromium
> 
> Which is not even close to the path in the error.
> 
> I attempted to set HOME env variable to ideally change the behavior but no luck.
> 
> Any suggestions? Thanks

You would run that command inside the container shell.

**Comment by discotimetraveler** [comment]
okay, thanks... I got it working, but yeah not exactly ideal with nearly 1GB of container data outside the container. =(  Hopefully this is resolved properly soon. Thanks again.

**Comment by holocronweaver** [comment]
For those stumbling upon this issue in the future, I got the solution by @samip5 working, documenting the exact steps here.

## The Workaround Steps

0. Set a non-root user in the Docker Compose file.
   ```yaml
   user: '1234:1234'
   ```

1. **Set the HOME environment variable** in your Docker Compose file to point to your storage path (instead of `/` which was causing the issue):
   ```yaml
   environment:
     - HOME=/data/home  # or whatever your storage path is
   ```

2. **Create/mount a volume** for that HOME path that your non-root user has write access to:
   ```yaml
   volumes:
     - /path/on/host:/data/home
   ```

3. **Run `npx playwright install` inside the container** to install the Playwright browsers in the correct location:
   ```bash
   docker exec -it <container_name> npx playwright install
   ```

## Why This Works

The root cause was that the HOME environment variable was defaulting to `/`, which made npm/Playwright try to use `/.cache/ms-playwright/...` for storing browser binaries. When running as non-root, the user doesn't have write permissions to the root directory.

By:
- Setting `HOME` to a writable path like `/data`
- Ensuring that path is mounted as a volume with proper permissions
- Running the Playwright install command to place the browsers in `$HOME/.cache/` (which now resolves to `/data/home/.cache/`)

The application can then successfully access and use the Playwright/Chromium executables for archiving links, even when running as a non-root user.

## Long Term Solution

Merge something like #779.
