### ISSUE TITLE
Perserving long scrolling pages (ChatGPT conversation)

### ISSUE THREAD

**Issue by ecker00** [linkwarden/linkwarden#508]
**Describe the bug**
When preserving a ChatGPT shared link, it only keeps the first part of the conversation. As it's loaded dynamically as you scroll the page, to read the entire chat.

**To Reproduce**
Make a share link to a long ChatGPT conversation and add to VaultWarden, the preserved version will be truncated.

**Expected behavior**
See the full conversation.

**Comment by daniel31x13** [comment]
I think this may be because of the way the conversations are "embedded" into the page, and that's because how Playwright (the library we're using for archiving) is working and detecting the end of the page incorrectly:
![image](https://github.com/linkwarden/linkwarden/assets/93432314/d9f998d8-a341-4896-9ce2-f0c576666ab6)

**Comment by ecker00** [comment]
Yeah, the only way I found reliably to preserve a conversation was poking around the HTML in browser, removing some `position: relative;` and `overflow-y: hidden;`, then use Vivialdi's feature of "Screenshot entire page". Should not be that hard for OpenAI to code a page which actually scrolls the document, not a child div. Oh well, sad it's not easy to fix.
