### ISSUE TITLE
Extremely high ressource usage - Is that normal?

### ISSUE THREAD

**Issue by Zottelchen** [linkwarden/linkwarden#540]
My problem is this: 
![ybjAJboDMO](https://github.com/linkwarden/linkwarden/assets/5148555/e0f1ee8b-bf1e-4492-a973-306badbb24db)

I imported my bookmarks from linkding (250 bookmarks) and my server slowed down noticeably. I let it run for quite a while, but it does not seem to improve. Is there a queue? Is it visible?

**Comment by GoodM4ven** [comment]
![image](https://github.com/linkwarden/linkwarden/assets/121377476/d34d94e5-f518-4468-84c1-0031c2b96f10)

This is my stats for the month since I also noticed the issue of the background scripts and fixed some values in the environment to fix them:

```env
ARCHIVE_TAKE_COUNT=1
ARCHIVE_SCRIPT_INTERVAL=30
``` 

Just double check the environment variables that are set in the worker and test them out accordingly:
https://github.com/linkwarden/linkwarden/blob/388b9d9184b0f782f4d7820710f9c8bca7d94afb/scripts/worker.ts#L8

**Comment by daniel31x13** [comment]
Yes that's normal. As @GoodM4ven mentioned, you can lower the `ARCHIVE_TAKE_COUNT` down to 1 (5 is the default).
It's basically the numbers of tabs it's opening (to archive links) behind the scenes divided by two, so `ARCHIVE_TAKE_COUNT=1` would be archiving the _first_ and _last_ unarchived link recursively until every link is archived.

**Comment by Zottelchen** [comment]
Okay, with the tweaks above it is usable and does not grind the server to a halt. Using 850MiB of memory when idle still is quite a lot though, for 250 bookmarks. I mean a postgres database holding millions of rows idles at ~500MiB.

**Comment by burgerga** [comment]
Maybe these variables can be added to the documentation?

My Linkwarden ran out of memory (4GB + 1GB swap) when processing (just a screenshot, nothing else) after the initial floccus sync, and the Linkwarden process was killed by the OOM killer :O 

Alternatively, Linkwarden could monitor it's RAM usage, and decide to not process an additional tab just yet?

**Comment by daniel31x13** [comment]
@burgerga for that I'm gonna have to use a queuing library, something like [BullMQ](https://github.com/taskforcesh/bullmq). It's already part of the (unscripted) roadmap.
