### ISSUE TITLE
Link URLs not editable

### ISSUE THREAD

**Issue by 2t9z16yo** [linkwarden/linkwarden#614]
**Describe the bug**
New user here. Installed the docker self hostable version. I was expecting the Edit link option would show the URL so that i could edit it

**To Reproduce**
1. Go to 'Edit Link' on any saved/imported link
2. See error

**Expected behavior**
I was expecting the Edit link option would show the URL so that i could edit it

**Screenshots**
See screenshot attached
<img width="652" alt="Screenshot 2024-06-03 at 11 05 41 PM" src="https://github.com/linkwarden/linkwarden/assets/122849678/bbf5b573-ee72-485f-ba29-6053d2b5acd5">

**Desktop (please complete the following information):**
 - Docker install
 - Browser [Arc]
 - Version [1.44.3]

**Additional context**
Btw, i used latest tag to install this but i'm getting v2.5.2. Even when i pull v2.5.3 instead of latest, its still showing 2.5.2 under Settings. I'm guessing its just a typo and not a versioning issue.

**Comment by silktrader** [comment]
Same here.

**Comment by daniel31x13** [comment]
This is intentional:  https://github.com/linkwarden/linkwarden/pull/455#issuecomment-1925686426

**Comment by 2t9z16yo** [comment]
thanks for the response. but that is not intuitive at all and i dont think it helps with the UX at all! this is a bookmark manager after all! so i would argue editing a link should be a mandatory feature. i can probably see editing feature as optional if linkwarden was intended to be used as Archivebox or Wallabag.

that said, the doc probably needs an update as it is shown as a feature available in the screenshot and explanation there.

would you entertain the link editing as an enhancement if i submit a feature request?

**Comment by jhickman** [comment]
I agree that URLs in a "bookmark manager" should be editable.  I recently updated my home DNS internal domain and I need to update a lot of bookmarks as the domain changed, but I'm unable to without a LARGE and cumbersome manual process.

If the URL is unable to be edited due to internal coding designs/decisions, then so be it.  Can I request a 'duplicate link' option that brings up a window with ALL link data pre-populated (tags, collections, etc) and give the user the ability to edit this new link?
