### ISSUE TITLE
Only 50 of preserved links are accessable

### ISSUE THREAD

**Issue by muuky** [linkwarden/linkwarden#758]
**Describe the bug**
I have more then 350 links archived in Linkwarden. Most of them are archived via API every day. 
But only recent 50 link's readable format is accesable, when i try to acess readable format, only got blank page.

For example)
When i have 70 links, number 1 ~ 20 link's readable format (`https://{myown}/presreved/:id?format=3`) returns blank. 
number 21 to 70 are showed properly.
After adding new links manually, number 21 link's readable format became not accessable, returns **blank page**.

But accessing broken link's readable format via API (`https://{myown}/api/vi/links/:id?format=3`), works properly. it returns proper json with contents in it.

**To Reproduce**
1. With 50 links stored, add new link.
2. 1st link's readable page format became blank

**Expected behavior**
All link's readable page shows properly

**Screenshots**
![20240910_093956](https://github.com/user-attachments/assets/9977d0b6-dfdc-4911-8809-43c0505fa18e)
upper screenshot is captured with API.

![20240910_094025](https://github.com/user-attachments/assets/978d0a4d-fab7-4296-9b3c-a4052b3b6d82)
uppper screenshot is captured via readable link

**Desktop (please complete the following information):**
 - OS: did't try
 - Browser 
 - Version 

**Smartphone (please complete the following information):**
 - Device: Iphone12
 - OS: iOS17.5.1
 - Browser : safari
 - Version: don't know

**Additional context**

**Comment by daniel31x13** [comment]
Linkwarden uses cursor based pagination for the links, so only the first 50 links are returned by default. To get the next batch you'll need to pass in the next cursor as a parameter:
```
http://localhost:3000/api/v1/links?cursor=20
```

**Comment by Danie10** [comment]
OK wait this is closed, but it does not seem right? I'm having the same issue, and surely it must be fixed in the code to work for end users? I have over 800 links, and it is going to be a bit odd to paste bits of code in to access each batch when I search for something. Or am I not understanding this correctly? I see my saved links but many of the Readable formats saved, open as a blank page (no error shown).

**Comment by daniel31x13** [comment]
@Danie10 yes you’re right, I closed this issue by accident - Thought the context was the API…

It will be fixed in the next upcoming release. 🔜

**Comment by Danie10** [comment]
@daniel31x13 Ah OK great thanks very much. I did note that the data is not lost because if some preserved formats have a download option, the file that downloads does in fact show the PDF, screenshot, etc. So is certainly more of a display issue I think. I did try setting `PAGINATION_TAKE_COUNT=20` but that did not seem to actually make any difference.

**Comment by daniel31x13** [comment]
> I did note that the data is not lost

Correct 👍
