### ISSUE TITLE
The option "Prevent duplicate links" does not work

### ISSUE THREAD

**Issue by yggcwx** [linkwarden/linkwarden#805]
**Describe the bug**
Even after selecting the “Preference”--“Link Settings”--“”Prevent duplicate links” “ option, it doesn't work at all. For example, when I import one html file and then import another html file, the duplicate links between them are not removed, and the total number of links is still the sum of all the links in the two files.

**Expected behavior**
Hopefully this bug will be fixed in the next version so that the option “Prevent duplicate links” will actually work!

![screenshot-1729733159079](https://github.com/user-attachments/assets/fe859035-fdf6-44f7-82a9-6146de0dd046)

**Comment by daniel31x13** [comment]
This isn’t a bug. The prevent duplicate link option only accounts for the links that are added individually. Via the “New Link” modal.

Linkwarden assumes the imported links are all clean from duplicates.

**Comment by yggcwx** [comment]
Then, it is recommended that subsequent versions can also have the function of detecting duplicate links and deleting them when importing HTML files.

**Comment by theAkito** [comment]
> Linkwarden assumes the imported links are all clean from duplicates.

Didn't know that. Now, I imported the same file multiple times, because the migration supposedly failed, when it didn't. It also didn't help, that the sort by date sort method simply does not work, as it does not respect link dates, at all.

Additionally, if you have an original database with a lot of links, import them into Linkwarden, then update your database, then how do you only import the diff between the old and the new database.

That said, obviously such presumption by the server should be documented somewhere.

**Comment by diskape** [comment]
Would you guys know why this duplicate link prevention does not work for certain websites?
For example: https://letterboxd.com/

This is with New Link and/or addon. No import used.

**Comment by SoCuul** [comment]
@daniel31x13 This seems to be broken in the latest version (v2.8.4), where duplicate links are not prevented from being added via the API (or in turn, by using the new link modal).
